### ISSUE TITLE
Metadata label should be "TI-RADS" instead of "TI RADS OLD"

### ISSUE THREAD

**Issue by sebarton69** [ACRCode/acr_assist_modules#1]
Metadata label should be "TI-RADS" instead of "TI RADS OLD":

https://github.com/ACRCode/acr_assist_modules/blob/705835ab169f33d4b4865b5f5b86dec4d58a55bd/Assist/TIRADS/TI-RADS_2.0.xml#L5

**Comment by smitakabra** [comment]
This has been worked on
