### ISSUE TITLE
Fix typos in LungRADS.xml

### ISSUE THREAD

**Issue by sebarton69** [ACRCode/acr_assist_modules#15]
The LungRADS.xml file (https://github.com/ACRCode/acr_assist_modules/blob/master/Assist/Lung-RADS/LungRADS.xml) contains the following typos...

- The Labels for all six <ChoiceDataElement Id="composition_#"...> elements need "Nodue" changed to "Nodule".

- The Labels for all six <MultiChoiceDataElement Id="significantAdditionalFindings_#"...> elements should be changed to "Are there any clinically significant findings?"

**Comment by smitakabra** [comment]
Thanks Steve for typo- 
The Labels for all six <ChoiceDataElement Id="composition_#"...> elements need "Nodue" changed to "Nodule" - has been fixed

for issue, i could see the question as you described, could you please let me know what is missing- The Labels for all six <MultiChoiceDataElement Id="significantAdditionalFindings_#"...> elements should be changed to "Are there any clinically significant findings?"

**Comment by sebarton69** [comment]
Sorry Smita, I should have been clearer on the second issue...
**"Are there any clinical significant finding?"** is the current label text, which does not sound grammatically correct because "clinical" is an adjective but is being used to describe "significant" which means an adverb should be used, and "Are" is a plural verb while "finding" is a singular noun.
**"Are there any clinically significant findings?"** seems like it would fix the problem.
Hopefully I'm making things clearer instead of more confusing.  Thanks.

**Comment by smitakabra** [comment]
Sorry Steve, I did not get this earlier. 

This has been fixed, please let me know for any issues.
