### ISSUE TITLE
Fix typos in CT_Stroke.xml

### ISSUE THREAD

**Issue by sebarton69** [ACRCode/acr_assist_modules#16]
In the CT_Stroke.xml file (https://github.com/ACRCode/acr_assist_modules/blob/master/CDE/NeuroCDE's/CT%20Stroke/CT_Stroke.xml), the Label and Hint for the <IntegerDataElement Id="midlineshift"...> element should have "midlineshift" changed to "Midline shift".

**Comment by smitakabra** [comment]
This has been fixed on the git.

**Comment by sebarton69** [comment]
The hint still contains "Midlineshift" instead of "Midline shift".
