### ISSUE TITLE
Fix typo in "Epidural Spinal.xml"

### ISSUE THREAD

**Issue by sebarton69** [ACRCode/acr_assist_modules#17]
In the "Epidural Spinal.xml" file (https://github.com/ACRCode/acr_assist_modules/blob/master/CDE/NeuroCDE's/Epidural%20Spinal%20CC/Epidural%20Spinal.xml), the ReportingModule/Metadata/Info/Description element should have "IEpidural" changed to "Epidural".

**Comment by smitakabra** [comment]
This has been fixed on the git.
