### ISSUE TITLE
Fix another typo in "Epidural Spinal.xml"

### ISSUE THREAD

**Issue by sebarton69** [ACRCode/acr_assist_modules#18]
In the "Epidural Spinal.xml" file (https://github.com/ACRCode/acr_assist_modules/blob/master/CDE/NeuroCDE's/Epidural%20Spinal%20CC/Epidural%20Spinal.xml), their is a choice label for the <ChoiceDataElement Id="POSTERIORELEMENTS"...> element that should have "Unilteral" changed to "Unilateral".

**Comment by smitakabra** [comment]
This has been fixed

**Comment by sebarton69** [comment]
Thank you.
